 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.dao.loginDAO;

/**
 *
 * @author Leandro Dias
 */
public class viewLogin extends javax.swing.JFrame {

    /**
     * Creates new form viewLogin
     */
    public viewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        Admin = new javax.swing.JButton();
        Funcionario = new javax.swing.JButton();
        imgIconLogin = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();
        PanelLoginFuncionario = new javax.swing.JPanel();
        jButtonLoginFuncionario = new javax.swing.JButton();
        txtPassFuncionario = new javax.swing.JPasswordField();
        txtLoginFuncionario = new javax.swing.JTextField();
        jLabelTextFuncionario = new javax.swing.JLabel();
        jLabelTextPassFuncionario = new javax.swing.JLabel();
        imgIconLoginFuncionario = new javax.swing.JLabel();
        jButtonExitFuncionario = new javax.swing.JButton();
        imgLoginFuncionario = new javax.swing.JLabel();
        PanelLoginAdmin = new javax.swing.JPanel();
        ButtonLoginAdmin = new javax.swing.JButton();
        txtPassAdmin = new javax.swing.JPasswordField();
        txtLoginAdmin = new javax.swing.JTextField();
        jLabelTextAdmin = new javax.swing.JLabel();
        jLabelTextPassAdmin = new javax.swing.JLabel();
        imgIconLoginAdmin = new javax.swing.JLabel();
        jButtonExitAdmin = new javax.swing.JButton();
        imgLoginAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelLogin.setMaximumSize(new java.awt.Dimension(626, 417));
        PanelLogin.setPreferredSize(new java.awt.Dimension(1366, 638));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        PanelLogin.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 260, 40));

        Funcionario.setText("Funcionário");
        Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioActionPerformed(evt);
            }
        });
        PanelLogin.add(Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 260, 40));

        imgIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlogin.png"))); // NOI18N
        PanelLogin.add(imgIconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 180, 90));

        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        PanelLogin.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1410, 620));

        getContentPane().add(PanelLogin, "card2");

        PanelLoginFuncionario.setMaximumSize(new java.awt.Dimension(626, 417));
        PanelLoginFuncionario.setPreferredSize(new java.awt.Dimension(1366, 638));
        PanelLoginFuncionario.setLayout(null);

        jButtonLoginFuncionario.setText("Login");
        jButtonLoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginFuncionarioActionPerformed(evt);
            }
        });
        PanelLoginFuncionario.add(jButtonLoginFuncionario);
        jButtonLoginFuncionario.setBounds(550, 430, 230, 30);

        txtPassFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassFuncionarioActionPerformed(evt);
            }
        });
        txtPassFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassFuncionarioKeyPressed(evt);
            }
        });
        PanelLoginFuncionario.add(txtPassFuncionario);
        txtPassFuncionario.setBounds(550, 380, 230, 30);

        txtLoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginFuncionarioActionPerformed(evt);
            }
        });
        PanelLoginFuncionario.add(txtLoginFuncionario);
        txtLoginFuncionario.setBounds(550, 290, 230, 30);

        jLabelTextFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextFuncionario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTextFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextFuncionario.setText("Funcionário:");
        PanelLoginFuncionario.add(jLabelTextFuncionario);
        jLabelTextFuncionario.setBounds(550, 250, 120, 25);

        jLabelTextPassFuncionario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTextPassFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextPassFuncionario.setText("Pass:");
        PanelLoginFuncionario.add(jLabelTextPassFuncionario);
        jLabelTextPassFuncionario.setBounds(550, 340, 47, 25);

        imgIconLoginFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlogin.png"))); // NOI18N
        PanelLoginFuncionario.add(imgIconLoginFuncionario);
        imgIconLoginFuncionario.setBounds(600, 80, 128, 128);

        jButtonExitFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonExitFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitFuncionarioActionPerformed(evt);
            }
        });
        PanelLoginFuncionario.add(jButtonExitFuncionario);
        jButtonExitFuncionario.setBounds(30, 520, 70, 70);

        imgLoginFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        PanelLoginFuncionario.add(imgLoginFuncionario);
        imgLoginFuncionario.setBounds(0, -10, 1366, 638);

        getContentPane().add(PanelLoginFuncionario, "card3");

        PanelLoginAdmin.setMaximumSize(new java.awt.Dimension(626, 417));
        PanelLoginAdmin.setPreferredSize(new java.awt.Dimension(1366, 638));
        PanelLoginAdmin.setLayout(null);

        ButtonLoginAdmin.setText("Login");
        ButtonLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginAdminActionPerformed(evt);
            }
        });
        PanelLoginAdmin.add(ButtonLoginAdmin);
        ButtonLoginAdmin.setBounds(600, 370, 200, 30);

        txtPassAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassAdminActionPerformed(evt);
            }
        });
        txtPassAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassAdminKeyPressed(evt);
            }
        });
        PanelLoginAdmin.add(txtPassAdmin);
        txtPassAdmin.setBounds(610, 280, 190, 30);

        txtLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAdminActionPerformed(evt);
            }
        });
        PanelLoginAdmin.add(txtLoginAdmin);
        txtLoginAdmin.setBounds(610, 190, 190, 30);

        jLabelTextAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextAdmin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTextAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextAdmin.setText("Admin:");
        PanelLoginAdmin.add(jLabelTextAdmin);
        jLabelTextAdmin.setBounds(610, 140, 80, 30);

        jLabelTextPassAdmin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTextPassAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextPassAdmin.setText("Pass:");
        PanelLoginAdmin.add(jLabelTextPassAdmin);
        jLabelTextPassAdmin.setBounds(610, 240, 90, 20);

        imgIconLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlogin.png"))); // NOI18N
        PanelLoginAdmin.add(imgIconLoginAdmin);
        imgIconLoginAdmin.setBounds(630, 40, 180, 90);

        jButtonExitAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonExitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitAdminActionPerformed(evt);
            }
        });
        PanelLoginAdmin.add(jButtonExitAdmin);
        jButtonExitAdmin.setBounds(40, 520, 70, 70);

        imgLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        PanelLoginAdmin.add(imgLoginAdmin);
        imgLoginAdmin.setBounds(0, 0, 1360, 620);

        getContentPane().add(PanelLoginAdmin, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        PanelLogin.setVisible(false);
        PanelLoginAdmin.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioActionPerformed
PanelLogin.setVisible(false);
PanelLoginFuncionario.setVisible(true);
    }//GEN-LAST:event_FuncionarioActionPerformed

    private void jButtonLoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginFuncionarioActionPerformed

        loginDAO dao = new loginDAO();

        if(dao.checkLogin(txtLoginFuncionario.getText(), txtPassFuncionario.getText())){
            new viewEmenta().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Senha incorreta!");
        }

    }//GEN-LAST:event_jButtonLoginFuncionarioActionPerformed

    private void txtPassFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassFuncionarioActionPerformed

    private void txtPassFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassFuncionarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginDAO dao = new loginDAO();

            if(dao.checkLogin(txtLoginFuncionario.getText(), txtPassFuncionario.getText())){
                new viewEmenta().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Senha incorreta!");
            }
        }
    }//GEN-LAST:event_txtPassFuncionarioKeyPressed

    private void txtLoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginFuncionarioActionPerformed

    }//GEN-LAST:event_txtLoginFuncionarioActionPerformed

    private void ButtonLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginAdminActionPerformed
      
             String nome = txtLoginFuncionario.getText();
        String pass = txtPassFuncionario.getText();
        if ((nome.equals("admin")) && (pass.equals("admin"))) {

            new viewAdmin().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Senha incorreta do Admin!");
        }
    }//GEN-LAST:event_ButtonLoginAdminActionPerformed

    private void txtPassAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassAdminActionPerformed

    private void txtPassAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassAdminKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassAdminKeyPressed

    private void txtLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAdminActionPerformed

    private void jButtonExitFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitFuncionarioActionPerformed
        PanelLogin.setVisible(true);
        PanelLoginFuncionario.setVisible(false);
    }//GEN-LAST:event_jButtonExitFuncionarioActionPerformed

    private void jButtonExitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitAdminActionPerformed
        PanelLogin.setVisible(true);
        PanelLoginAdmin.setVisible(false);
    }//GEN-LAST:event_jButtonExitAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton ButtonLoginAdmin;
    private javax.swing.JButton Funcionario;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelLoginAdmin;
    private javax.swing.JPanel PanelLoginFuncionario;
    private javax.swing.JLabel imgIconLogin;
    private javax.swing.JLabel imgIconLoginAdmin;
    private javax.swing.JLabel imgIconLoginFuncionario;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel imgLoginAdmin;
    private javax.swing.JLabel imgLoginFuncionario;
    private javax.swing.JButton jButtonExitAdmin;
    private javax.swing.JButton jButtonExitFuncionario;
    private javax.swing.JButton jButtonLoginFuncionario;
    private javax.swing.JLabel jLabelTextAdmin;
    private javax.swing.JLabel jLabelTextFuncionario;
    private javax.swing.JLabel jLabelTextPassAdmin;
    private javax.swing.JLabel jLabelTextPassFuncionario;
    private javax.swing.JTextField txtLoginAdmin;
    private javax.swing.JTextField txtLoginFuncionario;
    private javax.swing.JPasswordField txtPassAdmin;
    private javax.swing.JPasswordField txtPassFuncionario;
    // End of variables declaration//GEN-END:variables
}
