/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Dias
 */
public class viewEmenta extends javax.swing.JFrame {

    /**
     * Creates new form viewEmenta
     */
    public viewEmenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMesas = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        Utilizador = new javax.swing.JLabel();
        jButtonBackMesas = new javax.swing.JButton();
        jButtonMesa1 = new javax.swing.JButton();
        jButtonMesa2 = new javax.swing.JButton();
        jButtonMesa3 = new javax.swing.JButton();
        jButtonMesa4 = new javax.swing.JButton();
        jButtonMesa5 = new javax.swing.JButton();
        jButtonMesa6 = new javax.swing.JButton();
        jButtonMesa7 = new javax.swing.JButton();
        jButtonMesa8 = new javax.swing.JButton();
        jButtonMesa9 = new javax.swing.JButton();
        jButtonMesa10 = new javax.swing.JButton();
        jButtonMesa11 = new javax.swing.JButton();
        jButtonMesa12 = new javax.swing.JButton();
        jLabelMesas = new javax.swing.JLabel();
        imgPanelMesas = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        Utilizador1 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonEntradas = new javax.swing.JButton();
        jButtonPeixe = new javax.swing.JButton();
        jButtonCarne = new javax.swing.JButton();
        jButtonBebidas = new javax.swing.JButton();
        jLabelPeixe = new javax.swing.JLabel();
        jLabelCarne = new javax.swing.JLabel();
        jLabelEntradas = new javax.swing.JLabel();
        jLabelBebidas = new javax.swing.JLabel();
        imgPanelPrincipal = new javax.swing.JLabel();
        jPanelEntradas = new javax.swing.JPanel();
        panelEntrada = new java.awt.Panel();
        Utilizador2 = new javax.swing.JLabel();
        jButtonSalada = new javax.swing.JButton();
        jButtonBack2 = new javax.swing.JButton();
        jLabelSalada = new javax.swing.JLabel();
        jLabelPrecoSalada = new javax.swing.JLabel();
        jButtonPao = new javax.swing.JButton();
        jLabelPrecoPao = new javax.swing.JLabel();
        jLabelPao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        imgPanelEntrada = new javax.swing.JLabel();
        jPanelCarne = new javax.swing.JPanel();
        panelCarne = new java.awt.Panel();
        Utilizador3 = new javax.swing.JLabel();
        jButtonBack3 = new javax.swing.JButton();
        imgPanelCarne = new javax.swing.JLabel();
        jPanelBebidas = new javax.swing.JPanel();
        panelBebidas = new java.awt.Panel();
        Utilizador4 = new javax.swing.JLabel();
        jButtonBack4 = new javax.swing.JButton();
        imgPanelBebidas = new javax.swing.JLabel();
        jPanelPeixe = new javax.swing.JPanel();
        panelPeixe = new java.awt.Panel();
        Utilizador5 = new javax.swing.JLabel();
        jButtonBack5 = new javax.swing.JButton();
        imgPanelPeixe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 633));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.setLayout(null);

        Utilizador.setBackground(new java.awt.Color(0, 0, 0));
        Utilizador.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Utilizador.setText("Utilizador");
        panel2.add(Utilizador);
        Utilizador.setBounds(37, 24, 160, 40);

        jButtonBackMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonBackMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackMesasActionPerformed(evt);
            }
        });
        panel2.add(jButtonBackMesas);
        jButtonBackMesas.setBounds(37, 479, 70, 70);

        jButtonMesa1.setText("1");
        jButtonMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa1ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa1);
        jButtonMesa1.setBounds(154, 123, 103, 62);

        jButtonMesa2.setText("2");
        jButtonMesa2.setActionCommand("jButton1");
        jButtonMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa2ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa2);
        jButtonMesa2.setBounds(154, 199, 103, 64);

        jButtonMesa3.setText("3");
        jButtonMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa3ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa3);
        jButtonMesa3.setBounds(154, 290, 103, 62);

        jButtonMesa4.setText("4");
        jButtonMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa4ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa4);
        jButtonMesa4.setBounds(154, 363, 103, 62);

        jButtonMesa5.setText("5");
        jButtonMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa5ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa5);
        jButtonMesa5.setBounds(296, 123, 103, 149);

        jButtonMesa6.setText("6");
        jButtonMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa6ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa6);
        jButtonMesa6.setBounds(296, 290, 103, 135);

        jButtonMesa7.setText("7");
        jButtonMesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa7ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa7);
        jButtonMesa7.setBounds(437, 123, 103, 149);

        jButtonMesa8.setText("8");
        jButtonMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa8ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa8);
        jButtonMesa8.setBounds(437, 290, 103, 135);

        jButtonMesa9.setText("9");
        jButtonMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa9ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa9);
        jButtonMesa9.setBounds(580, 120, 103, 62);

        jButtonMesa10.setText("10");
        jButtonMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa10ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa10);
        jButtonMesa10.setBounds(580, 200, 103, 62);

        jButtonMesa11.setText("11");
        jButtonMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa11ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa11);
        jButtonMesa11.setBounds(580, 290, 103, 62);

        jButtonMesa12.setText("12");
        jButtonMesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa12ActionPerformed(evt);
            }
        });
        panel2.add(jButtonMesa12);
        jButtonMesa12.setBounds(580, 360, 103, 62);

        jLabelMesas.setText("Mesas");
        panel2.add(jLabelMesas);
        jLabelMesas.setBounds(100, 80, 80, 30);

        jPanelMesas.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1110, 560));

        imgPanelMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanelMesas.add(imgPanelMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));

        getContentPane().add(jPanelMesas, "card2");

        jPanelPrincipal.setMaximumSize(new java.awt.Dimension(626, 417));
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setLayout(null);

        Utilizador1.setBackground(new java.awt.Color(0, 0, 0));
        Utilizador1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Utilizador1.setText("Utilizador");
        panel1.add(Utilizador1);
        Utilizador1.setBounds(37, 24, 160, 40);

        jButtonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        panel1.add(jButtonBack1);
        jButtonBack1.setBounds(37, 479, 70, 70);

        jButtonEntradas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEntradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ementa/bread.png"))); // NOI18N
        jButtonEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntradasActionPerformed(evt);
            }
        });
        panel1.add(jButtonEntradas);
        jButtonEntradas.setBounds(360, 110, 140, 130);

        jButtonPeixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ementa/fish.png"))); // NOI18N
        jButtonPeixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeixeActionPerformed(evt);
            }
        });
        panel1.add(jButtonPeixe);
        jButtonPeixe.setBounds(530, 280, 140, 130);

        jButtonCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ementa/carne.png"))); // NOI18N
        jButtonCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarneActionPerformed(evt);
            }
        });
        panel1.add(jButtonCarne);
        jButtonCarne.setBounds(530, 110, 140, 130);

        jButtonBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ementa/water.png"))); // NOI18N
        jButtonBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBebidasActionPerformed(evt);
            }
        });
        panel1.add(jButtonBebidas);
        jButtonBebidas.setBounds(360, 280, 140, 130);

        jLabelPeixe.setText("Pratos de peixe");
        panel1.add(jLabelPeixe);
        jLabelPeixe.setBounds(530, 420, 120, 20);

        jLabelCarne.setText("Pratos de carne");
        panel1.add(jLabelCarne);
        jLabelCarne.setBounds(530, 250, 120, 20);

        jLabelEntradas.setText("Entradas");
        panel1.add(jLabelEntradas);
        jLabelEntradas.setBounds(370, 250, 130, 20);

        jLabelBebidas.setText("Bebidas");
        panel1.add(jLabelBebidas);
        jLabelBebidas.setBounds(360, 420, 130, 20);

        jPanelPrincipal.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1110, 570));

        imgPanelPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanelPrincipal.add(imgPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1400, 660));

        getContentPane().add(jPanelPrincipal, "card3");

        jPanelEntradas.setMaximumSize(new java.awt.Dimension(626, 417));
        jPanelEntradas.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelEntradas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelEntrada.setLayout(null);

        Utilizador2.setBackground(new java.awt.Color(0, 0, 0));
        Utilizador2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Utilizador2.setText("Utilizador");
        panelEntrada.add(Utilizador2);
        Utilizador2.setBounds(37, 24, 160, 40);

        jButtonSalada.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ementa/salad.png"))); // NOI18N
        jButtonSalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaladaActionPerformed(evt);
            }
        });
        panelEntrada.add(jButtonSalada);
        jButtonSalada.setBounds(570, 110, 140, 130);

        jButtonBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack2ActionPerformed(evt);
            }
        });
        panelEntrada.add(jButtonBack2);
        jButtonBack2.setBounds(37, 479, 70, 70);

        jLabelSalada.setText("Salada");
        panelEntrada.add(jLabelSalada);
        jLabelSalada.setBounds(570, 250, 50, 20);

        jLabelPrecoSalada.setText("2€");
        panelEntrada.add(jLabelPrecoSalada);
        jLabelPrecoSalada.setBounds(650, 250, 60, 14);

        jButtonPao.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ementa/bread.png"))); // NOI18N
        jButtonPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaoActionPerformed(evt);
            }
        });
        panelEntrada.add(jButtonPao);
        jButtonPao.setBounds(360, 110, 140, 130);

        jLabelPrecoPao.setText("2€");
        panelEntrada.add(jLabelPrecoPao);
        jLabelPrecoPao.setBounds(450, 260, 60, 14);

        jLabelPao.setText("Pão");
        panelEntrada.add(jLabelPao);
        jLabelPao.setBounds(360, 260, 50, 20);

        dataTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        dataTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(dataTable);

        panelEntrada.add(jScrollPane2);
        jScrollPane2.setBounds(780, 70, 310, 280);

        jPanelEntradas.add(panelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1110, 560));

        imgPanelEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanelEntradas.add(imgPanelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1400, 660));

        getContentPane().add(jPanelEntradas, "card4");

        jPanelCarne.setMaximumSize(new java.awt.Dimension(626, 417));
        jPanelCarne.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelCarne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCarne.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCarne.setLayout(null);

        Utilizador3.setBackground(new java.awt.Color(0, 0, 0));
        Utilizador3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Utilizador3.setText("Utilizador");
        panelCarne.add(Utilizador3);
        Utilizador3.setBounds(37, 24, 160, 40);

        jButtonBack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack3ActionPerformed(evt);
            }
        });
        panelCarne.add(jButtonBack3);
        jButtonBack3.setBounds(37, 479, 70, 70);

        jPanelCarne.add(panelCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1120, 560));

        imgPanelCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanelCarne.add(imgPanelCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1400, 660));

        getContentPane().add(jPanelCarne, "card5");

        jPanelBebidas.setMaximumSize(new java.awt.Dimension(626, 417));
        jPanelBebidas.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelBebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBebidas.setLayout(null);

        Utilizador4.setBackground(new java.awt.Color(0, 0, 0));
        Utilizador4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Utilizador4.setText("Utilizador");
        panelBebidas.add(Utilizador4);
        Utilizador4.setBounds(37, 24, 160, 40);

        jButtonBack4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack4ActionPerformed(evt);
            }
        });
        panelBebidas.add(jButtonBack4);
        jButtonBack4.setBounds(37, 479, 70, 70);

        jPanelBebidas.add(panelBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1110, 550));

        imgPanelBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanelBebidas.add(imgPanelBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1830, 700));

        getContentPane().add(jPanelBebidas, "card6");

        jPanelPeixe.setMaximumSize(new java.awt.Dimension(626, 417));
        jPanelPeixe.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelPeixe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPeixe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPeixe.setLayout(null);

        Utilizador5.setBackground(new java.awt.Color(0, 0, 0));
        Utilizador5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Utilizador5.setText("Utilizador");
        panelPeixe.add(Utilizador5);
        Utilizador5.setBounds(37, 24, 160, 40);

        jButtonBack5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButtonBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack5ActionPerformed(evt);
            }
        });
        panelPeixe.add(jButtonBack5);
        jButtonBack5.setBounds(37, 479, 70, 70);

        jPanelPeixe.add(panelPeixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1110, 560));

        imgPanelPeixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanelPeixe.add(imgPanelPeixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelPeixe, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
       jPanelMesas.setVisible(true);
       jPanelPrincipal.setVisible(false);
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButtonBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack3ActionPerformed
       jPanelPrincipal.setVisible(true);
       jPanelCarne.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBack3ActionPerformed

    private void jButtonBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack2ActionPerformed
         jPanelEntradas.setVisible(false);
         jPanelPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonBack2ActionPerformed

    private void jButtonBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack5ActionPerformed
         jPanelPeixe.setVisible(false);
         jPanelPrincipal.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBack5ActionPerformed

    private void jButtonBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack4ActionPerformed
        jPanelBebidas.setVisible(false);
         jPanelPrincipal.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBack4ActionPerformed

    private void jButtonEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntradasActionPerformed
         jPanelEntradas.setVisible(true);
         jPanelPrincipal.setVisible(false);
    }//GEN-LAST:event_jButtonEntradasActionPerformed

    private void jButtonBackMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackMesasActionPerformed
        viewLogin vp = new viewLogin();
        vp.setVisible(true);
    }//GEN-LAST:event_jButtonBackMesasActionPerformed

    private void jButtonMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa2ActionPerformed
        jPanelMesas.setVisible(false);
        jPanelPrincipal.setVisible(true); 
    }//GEN-LAST:event_jButtonMesa2ActionPerformed

    private void jButtonMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa5ActionPerformed
        jPanelMesas.setVisible(false);
        jPanelPrincipal.setVisible(true); 
    }//GEN-LAST:event_jButtonMesa5ActionPerformed

    private void jButtonMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa4ActionPerformed
       jPanelMesas.setVisible(false);
       jPanelPrincipal.setVisible(true); 
    }//GEN-LAST:event_jButtonMesa4ActionPerformed

    private void jButtonMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa6ActionPerformed
        jPanelMesas.setVisible(false);
        jPanelPrincipal.setVisible(true); 
    }//GEN-LAST:event_jButtonMesa6ActionPerformed

    private void jButtonMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa1ActionPerformed
        jPanelMesas.setVisible(false);
        jPanelPrincipal.setVisible(true);        

    }//GEN-LAST:event_jButtonMesa1ActionPerformed

    private void jButtonMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa3ActionPerformed
       jPanelMesas.setVisible(false);
       jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa3ActionPerformed

    private void jButtonMesa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa7ActionPerformed
      jPanelMesas.setVisible(false);
      jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa7ActionPerformed

    private void jButtonMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa8ActionPerformed
    jPanelMesas.setVisible(false);
    jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa8ActionPerformed

    private void jButtonMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa10ActionPerformed
      jPanelMesas.setVisible(false);
      jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa10ActionPerformed

    private void jButtonMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa11ActionPerformed
       jPanelMesas.setVisible(false);
       jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa11ActionPerformed

    private void jButtonMesa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa12ActionPerformed
     jPanelMesas.setVisible(false);
jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa12ActionPerformed

    private void jButtonMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa9ActionPerformed
        jPanelMesas.setVisible(false);
jPanelPrincipal.setVisible(true);   
    }//GEN-LAST:event_jButtonMesa9ActionPerformed

    private void jButtonSaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaladaActionPerformed

    private void jButtonPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaoActionPerformed
  DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
  
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonPaoActionPerformed

    private void jButtonCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarneActionPerformed
       jPanelPrincipal.setVisible(false);
       jPanelCarne.setVisible(true);   
    }//GEN-LAST:event_jButtonCarneActionPerformed

    private void jButtonBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBebidasActionPerformed
     jPanelPrincipal.setVisible(false);
       jPanelBebidas.setVisible(true);
    }//GEN-LAST:event_jButtonBebidasActionPerformed

    private void jButtonPeixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeixeActionPerformed
       jPanelPrincipal.setVisible(false);
       jPanelPeixe.setVisible(true);        
    }//GEN-LAST:event_jButtonPeixeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEmenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEmenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEmenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEmenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewEmenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Utilizador;
    private javax.swing.JLabel Utilizador1;
    private javax.swing.JLabel Utilizador2;
    private javax.swing.JLabel Utilizador3;
    private javax.swing.JLabel Utilizador4;
    private javax.swing.JLabel Utilizador5;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel imgPanelBebidas;
    private javax.swing.JLabel imgPanelCarne;
    private javax.swing.JLabel imgPanelEntrada;
    private javax.swing.JLabel imgPanelMesas;
    private javax.swing.JLabel imgPanelPeixe;
    private javax.swing.JLabel imgPanelPrincipal;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonBack2;
    private javax.swing.JButton jButtonBack3;
    private javax.swing.JButton jButtonBack4;
    private javax.swing.JButton jButtonBack5;
    private javax.swing.JButton jButtonBackMesas;
    private javax.swing.JButton jButtonBebidas;
    private javax.swing.JButton jButtonCarne;
    private javax.swing.JButton jButtonEntradas;
    private javax.swing.JButton jButtonMesa1;
    private javax.swing.JButton jButtonMesa10;
    private javax.swing.JButton jButtonMesa11;
    private javax.swing.JButton jButtonMesa12;
    private javax.swing.JButton jButtonMesa2;
    private javax.swing.JButton jButtonMesa3;
    private javax.swing.JButton jButtonMesa4;
    private javax.swing.JButton jButtonMesa5;
    private javax.swing.JButton jButtonMesa6;
    private javax.swing.JButton jButtonMesa7;
    private javax.swing.JButton jButtonMesa8;
    private javax.swing.JButton jButtonMesa9;
    private javax.swing.JButton jButtonPao;
    private javax.swing.JButton jButtonPeixe;
    private javax.swing.JButton jButtonSalada;
    private javax.swing.JLabel jLabelBebidas;
    private javax.swing.JLabel jLabelCarne;
    private javax.swing.JLabel jLabelEntradas;
    private javax.swing.JLabel jLabelMesas;
    private javax.swing.JLabel jLabelPao;
    private javax.swing.JLabel jLabelPeixe;
    private javax.swing.JLabel jLabelPrecoPao;
    private javax.swing.JLabel jLabelPrecoSalada;
    private javax.swing.JLabel jLabelSalada;
    private javax.swing.JPanel jPanelBebidas;
    private javax.swing.JPanel jPanelCarne;
    private javax.swing.JPanel jPanelEntradas;
    private javax.swing.JPanel jPanelMesas;
    private javax.swing.JPanel jPanelPeixe;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panelBebidas;
    private java.awt.Panel panelCarne;
    private java.awt.Panel panelEntrada;
    private java.awt.Panel panelPeixe;
    // End of variables declaration//GEN-END:variables
}
